Feature/reworkandfinish
diwise/integration-acoem pull request #1
Opened 2022-10-13 11:54 UTC by shestyf

2022-10-24 08:01 UTC, istyf requested changes
This PR needs some more attention

2022-10-24 08:01 UTC, istyf commented on internal/pkg/application/application.go
> +				DateTimeIfNotZero(properties.DateObserved, observed),
How could observed be zero here? IfNotZero seems unnecessary.

2022-10-24 08:01 UTC, istyf commented on internal/pkg/application/application.go
> +		jsonEnt, _ := json.MarshalIndent(entity, " ", "  ")
Do not marshal with indent (any more)

2022-10-24 08:01 UTC, istyf commented on internal/pkg/application/application.go
> +		fmt.Printf("entity: %s", jsonEnt)
Do not print to console

2022-10-24 08:01 UTC, istyf commented on internal/pkg/application/application.go
> +		_, err = i.cb.CreateEntity(ctx, entity, headers)
This will only work the first time we run. The next time you will get a conflict since the id will be the same every time you get data from the sensor. Attempt a merge first, and then perform a create if you get a 404 error.

2022-10-24 08:01 UTC, istyf commented on internal/pkg/application/application.go
> +	"Particles per cm3":          "Particles per cm3",
You can't pass this "propblemapa" to the broker. Figure this unit code out or omit the value.

2022-10-24 08:23 UTC, shestyf commented on internal/pkg/application/application.go
> +	"Particles per cm3":          "Particles per cm3",
I'll choose to omit since I  have yet to find a unit code for this value.

2022-11-30 22:08 UTC, istyf requested changes
Det finns fortfarande en del saker som behöver ses över här.

2022-11-30 22:08 UTC, istyf commented on go.mod
>  go 1.17
bumpa upp till 1.19

2022-11-30 22:08 UTC, istyf commented on go.mod
> +	github.com/diwise/service-chassis v0.0.0-20220609153321-22f72f7f5e21 // indirect
den här vill bli uppdaterad

2022-11-30 22:08 UTC, istyf commented on internal/pkg/application/application.go
> +		log.Error().Err(err).Msg("account id and account key must not be empty")
Men ändå fortsätter du? Detta borde kollas redan i New ovan. Antingen med en panic (eftersom vi förväntar oss att det redan hanterats när vi läste ut env-variablerna, eller genom att du returnerar (interface, error) från New.

2022-11-30 22:08 UTC, istyf commented on internal/pkg/application/application.go
> +				log.Error().Err(err).Msg("failed to create new entity")
Vad skall du göra med felet? Du kan ju inte fortsätta till Create som du gör här.

2022-11-30 22:08 UTC, istyf commented on internal/pkg/application/application.go
> +			Number(sensorNames[sensor.SensorName], sensor.Scaled, properties.UnitCode(unitCodes[sensor.UnitName])),
Någon form av check på att sensor name faktiskt finns din map borde finnas här.

2022-11-30 22:08 UTC, istyf commented on internal/pkg/application/application_test.go
>  func setupMockService(responseCode int, responseBody string) *httptest.Server {
Här skulle du kanske kunna lyfta in mock servicen från service chassis i stället.

2022-12-05 11:05 UTC, istyf approved these changes
/lgtm

2022-12-05 11:06 UTC, merged